export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const PUSH_NEW_PRODUCT = "PUSH_NEW_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const FULL_PRODUCT = "FULL_PRODUCT";
